version: 2.1
executors:
  node12:
    docker:
    - image: circleci/node:12
    environment:
      NPM_CONFIG_PREFIX: ~/.npm-global

commands:
  setup:
    steps:
    - checkout
    - run:
        name: install npm
        command: sudo npm -g install npm
    - run:
        name: Installing Dependencies
        command: npm ci
    - run:
        name: prepare test git user
        command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node12

    steps:
    - setup
    - run: mkdir junit
    - run:
        name: Lint
        command: npm run lint

    - run:
        name: Getting Code Coverage
        command: npm run test-ci

    - store_test_results:
        path: junit

    - store_artifacts:
        path: junit


workflows:
  version: 2
  build:
    jobs:
    - build
